Added link to legendmud.org client
SvarturH/legendhub pull request #158
Opened 2023-04-18 20:12 UTC by Ner-f

Added a link to the legendmud.org mud client.

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-18 21:01 UTC, steventhorne commented
Did you check that this looks good on all screen sizes?

You can use the dev tools (F12) and then the "Responsive Design Mode" button to test it out.

This is what it looks like in firefox, but it looks very similar in chrome.
![image](https://user-images.githubusercontent.com/3374032/232903525-8d60f218-e3c7-4df4-91be-2db873f7434f.png)

2023-04-19 12:12 UTC, Ner-f commented
> 

Looks good to me.

![image](https://user-images.githubusercontent.com/100298859/233070938-7c420d6d-f68c-454a-a49b-e15d6dcfb551.png)

2023-04-19 13:21 UTC, steventhorne requested changes
Looks good!

A couple of minor changes to the external link, though.

2023-04-19 13:21 UTC, steventhorne commented on www/src/views/shared/header.ejs
> +				<a class="nav-link" href="http://legendmud.org:19999/" target="_blank">Play Now</a>
When linking to external sites, in addition to `target="_blank"`, I also like to add `rel="noopener noreferrer"`. This is for SEO purposes.

2023-04-21 13:44 UTC, steventhorne approved these changes

2023-04-21 13:45 UTC, merged